[package]
name = "video-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"
video-rs = { version = "0.5.0", features = ["ndarray"] }
ffmpeg-next = "6.1.0"
image = "0.24.7"
plotters = "0.3"